# Generated by Django 4.1 on 2022-08-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='prince',
            new_name='price',
        ),
    ]
